# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='students',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojo_name',
            field=models.ForeignKey(default=87, on_delete=django.db.models.deletion.CASCADE, related_name='dojo', to='first_app.Dojo'),
            preserve_default=False,
        ),
    ]
