# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180619_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='dojo_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='first_app.Dojo'),
        ),
    ]
